# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - setup_remote_docker
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn test-compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "pom.xml" }}

      - run: mvn package

  release:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - setup_remote_docker
      - run: git config --global user.email "circleci@schuwalow.com"
      - run: git config --global user.name "cicleci"

      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn -B gitflow:release-start
      - run: mvn -B gitflow:release-finish

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
      - approve-release:
          type: approval
          requires:
            - test
          filters:
            branches:
              only:
                - develop
      - release:
          requires:
            - approve-release